name: buildx

on:
  pull_request:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Show available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: tomoasleep/k8s-avahi:${{ github.sha }}

      - uses: docker/build-push-action@v2
        if: contains(github.ref, 'master')
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: tomoasleep/k8s-avahi:latest
